/**
 * Synthetic labeled examples for the Stage 3 embedding classifier.
 * Run `pnpm seed:classifier` to generate embeddings and store the centroid.
 *
 * 100 positive (product feedback) + 100 negative (noise) examples.
 */

export const POSITIVE_EXAMPLES: string[] = [
  // Feature requests
  "The bulk export to CSV is missing column headers when you export more than 500 rows. We rely on this for our weekly data pipeline and it's breaking our scripts.",
  "I really wish there was a way to set up recurring workflows on a schedule. Right now we have to trigger everything manually which defeats the purpose of automation.",
  "Please add keyboard shortcuts for the most common actions. Power users like us navigate entirely by keyboard and the lack of shortcuts slows us down significantly.",
  "It would be incredibly useful if we could embed the dashboard as an iframe in our internal tools. Our ops team refuses to switch between three different tabs all day.",
  "The mobile app crashes every time I try to open a report with more than 10 charts. I can reproduce it 100% of the time on iOS 17.4 on my iPhone 15 Pro.",
  "Can you add a dark mode? Working late at night with this white interface is genuinely painful. Half our engineering team has asked for this.",
  "The search doesn't support fuzzy matching, so if I misspell a customer name slightly I get zero results. Even a basic 'did you mean' would help enormously.",
  "We need the ability to assign permissions at the folder level, not just at the workspace level. Our team structure requires per-project access control.",
  "The onboarding flow skips over the API key setup entirely. New users have no idea they need to configure that before the integrations work.",
  "Would love to see Salesforce as a supported CRM. We've been waiting on this for months and it's blocking our enterprise sales team from adopting the product.",
  "The Slack notifications have stopped working since your last deploy. The webhook URL is correct but nothing is coming through. This was working fine last week.",
  "I can't figure out how to delete a workspace. I've looked everywhere in settings and there's no option. Surely this has to be possible?",
  "The PDF report generation takes 4-5 minutes for reports with more than 20 pages. By the time it finishes, the data feels stale. Can you cache them?",
  "Our data hasn't synced from HubSpot in 3 days. The sync status shows 'active' but the records are clearly out of date. Something is silently failing.",
  "The filter panel loses all my selections when I navigate to another page and come back. I have to re-apply six filters every single time. Incredibly frustrating.",
  "Please support multi-select for the theme assignment. A single piece of feedback can clearly relate to multiple themes but I can only pick one.",
  "The API rate limits are too aggressive. We're hitting 429s just doing routine syncs. Our enterprise plan should allow higher throughput.",
  "I love the new dashboard — the real-time updates are exactly what we needed. But the charts don't render correctly on Firefox. Tested on Chrome and it's fine.",
  "Could you add a 'duplicate workflow' button? Creating new automations from scratch every time is tedious when most of our workflows are variations of the same base.",
  "The tooltip for the sentiment score doesn't explain what the scale means. Is -1 the worst or the best? New users will have no idea without documentation.",
  "We're getting duplicate feedback items from Intercom. The same conversation appears 2-3 times in the table. Looks like your deduplication logic has a bug.",
  "The import from Gong is only picking up the first speaker turn from each call. We're losing all the back-and-forth context that makes the transcript useful.",
  "Please add a way to bulk archive resolved items. We have 800+ resolved feedback items cluttering our view and no way to clean them up at scale.",
  "The Linear integration creates tickets but doesn't sync the status back. If someone closes the ticket in Linear, it should update in Voxly automatically.",
  "Timestamps in the UI are showing in UTC but our team is distributed and we need timezone-aware display. Can we set a workspace timezone preference?",
  "The theme clustering seems to be grouping completely unrelated issues together. 'Mobile app sync' and 'PDF export' are ending up in the same theme somehow.",
  "I tried to connect our G2 account but the OAuth flow gives a 500 error after I click 'Allow'. I've tried three browsers and two different G2 accounts.",
  "The weekly digest email is missing the top themes by ARR impact that you advertised. It only shows volume, which isn't the metric we care about.",
  "Autocomplete on the assignee field shows deleted users. It's confusing and occasionally causes items to be assigned to someone who left the company.",
  "We need SSO via Okta. Our IT policy requires all SaaS tools to go through Okta and we can't get approval to roll out Voxly until this is supported.",
  "The severity inference is classifying almost everything as 'medium'. It doesn't seem to be accounting for customer tier at all. Enterprise bugs should be high.",
  "Would it be possible to add a confidence indicator to the AI summary? Sometimes the summary is confidently wrong and there's no way to know how to trust it.",
  "The real-time preview of the workflow builder node config doesn't update until I click 'Save'. It should show me what the filter will match as I type.",
  "Pasting formatted text from Notion into the feedback verbatim field strips all the markdown. The plain text result is often hard to read without formatting.",
  "The 'Last 7 days' smart view is showing items from 8 and 9 days ago. There's an off-by-one bug in the date filter boundary.",
  "We'd love a Canny importer to migrate our historical feedback. We're switching from Canny and don't want to lose two years of customer data.",
  "The table doesn't persist column widths between sessions. Every time I log in I have to resize the columns to fit my workflow. Please save this preference.",
  "Clicking 'Create Linear ticket' from the detail panel generates a ticket with the wrong workspace. It's defaulting to my personal workspace instead of the team one.",
  "The customer tier badge in the table is missing for about 30% of our Enterprise customers. The CRM sync isn't enriching all of them.",
  "We really need webhooks for workflow outputs so we can pipe results into our internal tooling. Right now we can only send to Slack or create a Linear ticket.",
  "It's impossible to see which connector a feedback item came from once it's in the table without clicking into the detail panel. A column for source would help.",
  "The sentiment chart on the themes page shows all bars the same height. It looks like a rendering bug — the values are different but the display is identical.",
  "I created a workflow filter for Enterprise customers but it's triggering on Growth customers too. The tier condition doesn't seem to be evaluating correctly.",
  "Please add an audit log so we can see who archived or re-opened feedback items. We need this for SOC 2 compliance.",
  "The Slack connector only supports public channels. We keep our customer feedback in a private channel and there's no way to connect it.",
  "Your AI-generated theme names are occasionally nonsensical. 'Thing that breaks often' appeared as a theme name last week. The naming prompt needs work.",
  "Multi-factor authentication isn't enforced at the workspace level. Our security team requires we can mandate MFA for all members.",
  "The feedback table loads fine on desktop but on a 13-inch laptop the columns overlap and the text becomes unreadable. Responsive layout is needed.",
  "Can you add a 'copy verbatim text' button in the detail panel? Right now I have to manually select and copy which is clunky when sharing evidence with engineers.",
  "The theme spike notifications are going to everyone in the workspace rather than just the assignees. This is creating too much noise for our team.",

  // Bug reports
  "Every time I try to export a theme summary to Notion it creates a blank page. The API call seems to succeed (no error) but the content never appears.",
  "Keyboard navigation breaks inside the filter dropdown. After I open it with Enter, I can't navigate the options with arrow keys. Had to switch back to mouse.",
  "The chart tooltips in the trends view appear behind the navigation bar on screens below 1440px width. You can see part of them but they're obscured.",
  "After our recent SSO migration, about 15 of our users can't log in even though they exist in Clerk. They get a 'workspace not found' error on the dashboard.",
  "The workflow 'test run' feature fails with a timeout if the feedback item has no customer enrichment data. It should handle missing enrichment gracefully.",
  "Resizing the browser window while the detail panel is open causes the panel to disappear. I have to click on the row again to re-open it.",
  "The 'unassigned' filter in the smart view is also hiding items assigned to deactivated users, which shouldn't count as assigned.",
  "Uploading a CSV with special characters in the customer name field causes a 422 error with no useful error message. Japanese characters specifically.",
  "The pagination in the feedback table resets to page 1 every 30 seconds due to the auto-refresh. You can't stay on page 5 without it jumping back.",
  "Notifications for workflow runs are sent even when the run fails. We're being alerted about successful actions that never actually happened.",
  "The 'resolved' status badge color is the same grey as 'archived'. It's impossible to distinguish between them in the table at a glance.",
  "The sidebar connector count shows negative numbers after I archived and re-imported a batch of items. The item_count decrement has a bug.",
  "The feedback detail panel's scrollbar overlaps with the action buttons on Windows Chrome. The layout needs padding adjustments for Windows scrollbar width.",
  "Session timeout during a long workflow builder session silently fails and loses all unsaved changes. There should be a prompt or auto-save.",
  "The email digest is being sent at 2am UTC regardless of workspace timezone settings. For our US team, this arrives in the middle of the night.",
  "When you filter by multiple themes simultaneously, the count in the view tab shows the sum of each theme independently rather than the intersection.",
  "Deleting a connector doesn't remove its associated feedback items from the table. We have orphaned items with no source connector.",
  "The Intercom connector is ingesting bot conversation starters that are clearly automated, even with bot filtering enabled in the settings.",
  "The 'Create theme from selection' action creates the theme but doesn't assign the selected items to it. You have to do that step manually.",
  "The feedback item age calculation shows '0 minutes ago' for items published within the same day they were ingested. The age should reflect published_at, not ingested_at.",
  "The CSV export from the Themes page includes all items, not just those matching the current filter. The export button should respect the active view.",
  "Our webhook endpoint keeps getting disabled after 10 failed delivery attempts. There's no way to re-enable it without disconnecting and reconnecting the entire connector.",
  "Sorting the table by sentiment shows NaN values at the top rather than treating them as neutral. Null sentiment items should sort consistently.",
  "The 'Merge into theme' action loses the original theme_confidence score on the merged items, replacing it with null. This breaks our theme analytics.",

  // Usability / UX
  "I spent 20 minutes looking for where to set up the HubSpot sync schedule before I found it buried in 'Advanced connector settings'. This needs to be more discoverable.",
  "The workflow builder is powerful but the learning curve is steep. A guided tutorial with an interactive first workflow would make this much more approachable.",
  "The feedback table loads 50 items by default but our team prefers to see 200. Please add a configurable page size that persists between sessions.",
  "It's not obvious that you can click the theme badge to filter by that theme. There's no cursor change or hover state to indicate it's clickable.",
  "The empty state for the inbox shows a generic message. It would be much more useful to explain what types of items end up here and how to resolve them.",
  "Error messages when a connector fails are too technical. 'ECONNREFUSED 127.0.0.1:5432' means nothing to a PM. Show a user-friendly description instead.",
  "The 'Add evidence to Linear ticket' flow requires me to type the ticket ID manually. I'd rather have a searchable dropdown of my open Linear tickets.",
  "Switching between workspaces takes 3-4 seconds with a blank loading screen. This feels much slower than it needs to be. Can you cache the workspace data?",
  "The date range picker in the filter panel doesn't have quick options like 'last 30 days' or 'this month'. I have to manually select start and end dates every time.",
  "The feedback verbatim text in the table is truncated at exactly 80 characters regardless of the row height. A smarter truncation based on available space would be better.",
  "I can't find a way to export the list of themes with their item counts for a board presentation. A simple CSV export from the themes page is all I need.",
  "The connectors page doesn't show which connectors are experiencing errors. I only discovered our Zendesk connector was broken when a customer told us.",
  "Selecting all rows with the header checkbox and then clicking 'Bulk archive' doesn't work when you're on filtered views. It archives the wrong items.",
  "The activity log in the detail panel doesn't show when the AI summary was last generated or what triggered a re-generation.",
  "Navigating back from the workflow builder discards all unsaved progress without any confirmation prompt. This has caused me to lose 30 minutes of work twice.",
  "When I @mention a teammate in a comment on a feedback item, they don't receive any notification. The mention feature is completely silent.",
  "The 'Themes' tab in the sidebar shows a number badge for item count but it doesn't update in real time like the Inbox badge does.",
  "Please add column grouping to the table — I'd like to be able to group feedback by theme and collapse/expand each group.",
  "The detail panel should have a 'next/previous' navigation to move between items without closing and reopening the panel.",
  "I need to be able to schedule the weekly briefing at a time that makes sense for my team. The fixed Tuesday morning delivery doesn't work for our Asia-Pacific team.",
]

export const NEGATIVE_EXAMPLES: string[] = [
  // Billing/account noise
  "Hi, I forgot my password and can't log in. Can you send me a reset link? My email is sarah@company.com",
  "I was charged twice for my subscription this month. Please refund the duplicate charge. My invoice number is INV-2024-8834.",
  "Can you change the email address on my account? I'm moving to a new company domain.",
  "I want to cancel my subscription immediately. Please confirm cancellation and refund the unused portion of my annual plan.",
  "How do I upgrade from the Starter plan to the Growth plan? I don't see an upgrade button on the billing page.",
  "I need a copy of my invoice for March 2024 for expense reimbursement. Please send it to billing@company.com.",
  "Our credit card expired and the subscription lapsed. How do I update our payment method to reactivate the account?",
  "I accidentally deleted a user from our workspace. How do I re-invite them?",
  "We need to add five more seats to our account. Who do I contact for pricing?",
  "I'm getting an error saying my email is already in use when I try to sign up. I don't think I've ever created an account with you before.",
  "Please remove all data associated with my account per GDPR. This is a formal deletion request.",
  "Can I get a receipt for the payment that went through on the 15th? Our accounting team needs it for Q4 close.",
  "I think I'm being charged for a plan I didn't sign up for. Can you look into this?",
  "How do I switch from monthly to annual billing to get the discount?",
  "The discount code SUMMER25 isn't applying at checkout. Is it still valid?",

  // Generic support / access issues
  "I can't log in. The page just shows a loading spinner forever.",
  "Hello! I just wanted to say your support team was incredibly helpful. John was amazing and resolved my issue in minutes.",
  "What are your business hours? I need to talk to someone urgently.",
  "Is there a status page where I can check if there's an outage? The service seems down right now.",
  "I'd like to request a demo for my team. Who should I contact?",
  "Do you have a free trial? I want to test this before committing to a paid plan.",
  "How do I transfer my account to a new owner? I'm leaving the company.",
  "I was referred by a friend. Where do I enter the referral code to get the discount?",
  "What's your company's data residency policy? Our legal team wants to know where data is stored.",
  "I need to know your SOC 2 compliance status for a vendor security questionnaire.",
  "We had a scheduled call with your sales team at 3pm EST and nobody joined. Can we reschedule?",
  "Can you whitelist our IP address for API access? Our firewall blocks outbound connections by default.",
  "I'm a journalist writing about B2B SaaS tools. Can I speak with someone from your communications team?",
  "Do you offer nonprofit discounts? We're a 501(c)(3) and can't afford enterprise pricing.",
  "I'm trying to authenticate with the API but keep getting 401 Unauthorized. I've triple-checked the key and it looks correct.",

  // Spam / noise / personal
  "Congratulations! You've been selected for a special offer. Click here to claim your prize.",
  "We're looking to partner with your company on an exciting new initiative. Please reach out to our BD team.",
  "I'm a student writing a dissertation on SaaS product management. Would anyone be willing to fill out a 10-minute survey?",
  "Just checking in to see if you received my previous email from last week.",
  "Happy Monday everyone! Excited for the week ahead.",
  "Has anyone else noticed that the weather in San Francisco has been really nice lately?",
  "Reminder: team all-hands is at 2pm PST in the main conference room.",
  "Looking for a senior PM role in the SF Bay Area. DMs open.",
  "This is a test message please ignore.",
  "asd asd asd test 123",
  "I'm forwarding this to the right department for follow-up.",
  "Thanks for getting back to me so quickly! You've resolved everything I needed.",
  "Great product by the way, really enjoying it overall. Keep up the good work!",
  "I'll send more details in a follow-up email.",
  "Please disregard my previous message. I figured it out.",

  // Billing escalations that aren't product feedback
  "I've now sent three emails about this overcharge with no response. I'm going to dispute the charge with my bank if this isn't resolved by Friday.",
  "Your billing system charged my card without authorization. This is fraud and I'm reporting it.",
  "I asked for a refund two weeks ago. Still waiting. This is unacceptable.",
  "Where is my invoice? I've asked three times now. My accounting department is waiting.",
  "I was promised a custom enterprise contract and never received it. What happened?",
  "The pricing on your website says $49/month but I was charged $59. Please explain.",
  "I want to speak to a manager about my billing dispute.",
  "Your auto-renewal policy is buried in the terms and conditions. This is a deceptive practice.",
  "I need a W-9 form for our vendor records. Please send it to ap@company.com.",
  "We haven't received the SLA document we were promised during the sales process.",

  // Generic compliments without product signal
  "Your company is great! Love the product! Keep it up!",
  "Five stars! Best tool we've used this year. No complaints.",
  "Just wanted to say thank you to the whole team.",
  "You guys are doing an amazing job. Really appreciate everything.",
  "The onboarding call was fantastic. Sarah was so helpful.",
  "Highly recommend to anyone in the product space.",
  "We're thrilled with the results so far. Really happy customers here.",
  "Congrats on the product launch! Looking forward to seeing what's next.",
  "Your CEO's blog post was excellent. Very insightful.",
  "Love the company culture you're building. Keep it up!",

  // Password / auth noise
  "My two-factor authentication code isn't working. The app keeps saying it's invalid.",
  "I'm locked out of my account after too many failed login attempts. How long does the lockout last?",
  "SSO stopped working for my account this morning. I get redirected to a blank page after authenticating.",
  "I reset my password but the new password isn't being accepted. It meets all the requirements shown.",
  "Can I remove 2FA from my account? I've lost access to my authenticator app.",
  "My session keeps expiring after 15 minutes even though I'm actively using the app.",
  "I've been getting phishing emails pretending to be from your company. Wanted to flag this.",
  "How long are magic link emails valid? Mine keeps expiring before I can click it.",
  "I don't receive the verification email on sign-up. Checked spam folder too.",
  "My Google SSO is working but my Okta SSO is not. Can you check your Okta configuration?",

  // Hiring / partnerships / press
  "I'm interested in applying for a software engineering role at your company. Is there a careers page?",
  "We'd love to explore a technology partnership between our companies. Who should I reach out to?",
  "I'd like to feature your product in an upcoming webinar. Can I get a demo license?",
  "Your company was mentioned in a recent Gartner report. Congratulations!",
  "I'm an investor interested in learning more about your growth metrics. Can we set up a call?",
  "We're building an integration marketplace and would like to list your product. Who handles partnerships?",
  "Can I use your logo in a 'powered by' attribution on our website?",
  "We're a reseller interested in your partner program. Please send us information.",
  "I'm a product manager at a competing company. Would love to grab coffee and swap notes.",
  "Your product was recommended in a Reddit thread I was reading. Just signed up!",

  // Off-topic internal comms leaked into feedback channel
  "Team — reminder to submit your timesheets by EOD Friday.",
  "The office will be closed on Monday for the holiday.",
  "Pizza is available in the kitchen for the next 30 minutes.",
  "Quarterly planning documents have been shared in the Google Drive folder.",
  "Does anyone have the Wi-Fi password for the conference room?",
  "Heads up: the elevator in Building B is out of service until Thursday.",
  "Parking validation is available at the front desk.",
  "The weekly standup has been moved to 10am starting next week.",
  "Please update your emergency contact information in HR by the end of the month.",
  "All-hands recording is now available in Notion. Link in #announcements.",

  // Compliance / legal / data requests
  "Please send me a copy of all data you hold about me under GDPR Article 15.",
  "We require a Data Processing Agreement before we can proceed with our purchase.",
  "Can you confirm your HIPAA compliance status? We work in healthcare.",
  "We need your privacy policy in a machine-readable format for our vendor assessment.",
  "I'm the legal representative for a user who has passed away. How do I close the account?",
]
