// Synthetic labeled examples for seeding the embedding classifier centroid.
// 100 product feedback examples + 100 non-feedback examples.
// The centroid is computed as the average embedding of the positive examples.
// In production, bootstrapClassifierCentroid() is called once on workspace creation.

export const FEEDBACK_EXAMPLES: string[] = [
  "The mobile sync is constantly dropping. I lose work every time I switch devices.",
  "Would love a way to bulk export all my data as CSV. Currently have to do it one page at a time.",
  "The PDF export feature doesn't preserve our custom fonts. This is a blocker for our design team.",
  "Dark mode would make this so much more usable for late-night work sessions.",
  "The onboarding flow is confusing. I had no idea where to start after signing up.",
  "Your search is too slow. Queries over 10k records take 8+ seconds.",
  "The API rate limits are too low for our enterprise use case. We need at least 10x the current limit.",
  "Love the new dashboard. The charts finally make sense and load fast.",
  "Two-factor authentication is missing. Our security team won't approve this tool without it.",
  "The Slack integration breaks whenever we rename a channel. Please fix this.",
  "Can you add keyboard shortcuts? Power users like me live by the keyboard.",
  "The mobile app crashes on iOS 17 when I try to open large files.",
  "Please add a Jira integration. Switching back and forth between apps is killing our workflow.",
  "The column resizing in the table view resets every time I refresh the page.",
  "Your SSO support is missing Azure AD. That's a dealbreaker for us.",
  "The notification system is too noisy. I'm getting emails for every tiny update.",
  "Love the recent performance improvements. The app feels 10x snappier.",
  "When I delete a project, related tasks should be deleted too, not orphaned.",
  "The activity log is missing timestamps. I need to know exactly when things happened.",
  "Your pricing page doesn't explain what happens at the end of the trial. Very confusing.",
  "We need role-based access control. Right now everyone can see everything.",
  "The autocomplete in the search bar suggests deleted items. Please fix.",
  "Importing from Google Sheets is broken — it fails on any file over 5MB.",
  "The undo history only goes back 10 steps. That's not enough for complex edits.",
  "Please add a recurring task feature. We have weekly processes we do manually.",
  "The dashboard widgets can't be rearranged. We need to customize the layout.",
  "Your API documentation is outdated. The v2 endpoints aren't documented at all.",
  "The email digest is sent at 3am my time. Please add timezone settings.",
  "Love the new AI suggestions feature. Saved me hours this week.",
  "Comments on tasks should support markdown formatting.",
  "The calendar view doesn't show tasks that span multiple days correctly.",
  "Please add a way to archive old projects without deleting them.",
  "The filter panel closes every time I change a value. Very annoying for multi-filter setups.",
  "Your iOS app doesn't support Face ID login. Has to be added.",
  "The bulk action toolbar disappears when I scroll. Please keep it fixed.",
  "Can you add CSV import? Migrating from our old tool is a huge manual process.",
  "The loading spinner never goes away on the analytics page. Infinite load.",
  "Sub-tasks would be incredibly useful. Our projects have complex hierarchies.",
  "The drag-and-drop on mobile is basically unusable. Too sensitive.",
  "Please let us customize the email notification templates. We want our branding.",
  "The report generation is way too slow. 2 minutes for a simple export is unacceptable.",
  "I love how fast the table loads now compared to 6 months ago. Great improvement.",
  "The timeline view is missing dependency arrows between tasks.",
  "Please add a read-only sharing link for stakeholders who don't need editing access.",
  "The workspace switcher is buried in settings. Should be one click from anywhere.",
  "Your webhooks don't include enough context. We need the full object, not just the ID.",
  "The chart colors are not accessible — low contrast for color-blind users.",
  "Automatic backups would give us peace of mind. Right now we do it manually.",
  "Please add a changelog or version history for documents.",
  "The onboarding checklist was super helpful. Really got me up to speed fast.",
  "Multi-select on mobile requires a long press, which conflicts with scrolling.",
  "We need a sandbox/staging environment that's separate from production.",
  "The formula editor crashes the browser tab on complex functions.",
  "Tags should be color-coded. Right now they all look the same.",
  "Please support Markdown in the description fields, not just the comment box.",
  "The integration with Salesforce breaks every time Salesforce does a release.",
  "Conditional logic in forms would unlock a huge number of use cases for us.",
  "The 'recently viewed' list resets when I clear browser cache. Should sync to my account.",
  "Offline mode would be a game changer for our field team.",
  "The search results don't highlight the matched keywords. Hard to scan.",
  "Please add a way to mention team members in comments with @-mentions.",
  "The permission system is too all-or-nothing. We need field-level permissions.",
  "Your mobile push notifications are delayed by 10-15 minutes. Useless for urgent alerts.",
  "The gantt chart doesn't auto-adjust when I drag a task. It just overlaps others.",
  "Please add a monthly summary email. Would help leadership track progress.",
  "The copy-paste between tables loses all formatting. Very frustrating.",
  "I want to be able to pin important items to the top of any list view.",
  "The trial expiry notice comes 1 day before, not 7 days. Very little time to decide.",
  "We love the new AI tagging feature. Saves us significant manual work.",
  "The two-pane layout would benefit from a resizable divider.",
  "Please add time tracking. We need to log hours against tasks for billing.",
  "Exporting to PDF crops the right side of wide tables.",
  "Guest access without requiring a sign-up would help us share work with clients.",
  "The status field should support custom values, not just your preset list.",
  "Filtering by 'no assignee' is missing from the filter options.",
  "We need a proper audit log for compliance. Who changed what and when.",
  "The onboarding video is 15 minutes long. Nobody watches that. Make it 3.",
  "Auto-save works but doesn't show any visual indicator that it saved.",
  "The global search doesn't search inside attachments. Needs full-text search.",
  "Please add a dark theme to the mobile app too, not just desktop.",
  "The side panel is too narrow on 13-inch screens. Content is clipped.",
  "Duplicate detection when importing would save us from cleaning up tons of dupes.",
  "We need an integration with Notion. Our docs team lives there.",
  "The sorting resets to default every time I navigate away and back.",
  "It would be great to have AI-generated meeting notes from transcripts.",
  "The color picker for labels is too limited. We need custom hex values.",
  "Please add keyboard navigation to the command palette.",
  "The new onboarding UI is much cleaner than the old one. Great job.",
  "The analytics page would be much better with year-over-year comparison.",
  "Dependency management across projects is completely missing.",
  "The mention notifications in email don't link back to the right context.",
  "We need a Zapier integration. Our automation workflows depend on it.",
  "The public API should support OAuth2, not just API keys.",
  "Printing from the app produces terrible output. Margins are off everywhere.",
  "The file preview for PDFs is very slow — takes 20 seconds to load a 2MB file.",
  "I'd love an AI assistant that could help me write task descriptions.",
  "The emoji picker in comments is missing the skin tone selector.",
  "The card view is great but needs a compact mode for dense projects.",
  "Please add localization. We have a global team and need non-English UI.",
  "The date picker doesn't respect my locale for week start (Monday, not Sunday).",
  "Your REST API returns 200 for errors instead of proper 4xx/5xx codes.",
]

export const NOISE_EXAMPLES: string[] = [
  "Hi, I forgot my password. Can you help me reset it?",
  "Invoice #2847 shows a charge of $299 but we're on the $99 plan. Please fix.",
  "Please cancel my subscription immediately.",
  "I was double charged this month. Please issue a refund.",
  "Hello, I'm a marketing consultant and I wanted to reach out about a partnership opportunity.",
  "Can you send me an updated invoice for our records?",
  "How do I update my billing credit card?",
  "We need to downgrade to the starter plan before our renewal.",
  "This is John from IT, just testing the webhook endpoint. Ignore this.",
  "Hello there! We offer high-quality SEO services at affordable prices.",
  "Hi team, can someone approve my PTO request for next week?",
  "The conference call is at 3pm. Please use the dial-in code 847-293.",
  "Happy birthday! 🎂",
  "I'm trying to log in but getting an error saying my account is suspended. Can you unsuspend it?",
  "This is an automated notification from your CI/CD pipeline. Build #4821 passed.",
  "Please verify your email address to continue.",
  "Your trial has expired. Upgrade to continue using the service.",
  "Hi, I think I accidentally created two accounts. Can you merge them?",
  "Can I get a copy of our MSA signed in 2022?",
  "Reminder: team all-hands is at noon tomorrow in the Zoom link below.",
  "Our account admin left the company. How do we transfer ownership?",
  "We'd like to request a copy of your SOC 2 report.",
  "Please add info@example.com as a billing contact.",
  "I'm getting a 404 when trying to access my account. Is there an outage?",
  "Hi, I'm locked out of my account. Two-factor authentication isn't working because I lost my phone.",
  "Can you whitelist IP 192.168.1.1 for our office?",
  "This is a test message. Please disregard.",
  "Congratulations! You've been selected for a special offer.",
  "Could we get a W-9 form for our records?",
  "Hi, how much does the enterprise plan cost?",
  "What's your refund policy?",
  "We're evaluating tools and would like a demo. Are you available Thursday?",
  "Hi, this is Sarah from accounting. Please send invoices to invoices@example.com from now on.",
  "My account shows 'Payment failed'. How do I update my card?",
  "Can I get a discount for annual billing?",
  "What integrations do you support? Do you have a Salesforce connector?",
  "We need a BAA signed for HIPAA compliance. Please send it over.",
  "I'm writing to request a data deletion under GDPR Article 17.",
  "Please remove me from your mailing list.",
  "Hi, we're migrating to a new domain. Can you update our email from old@co.com to new@co.com?",
  "Can we get a bulk discount for 200 seats?",
  "The login page is down. Nobody on our team can access the app.",
  "Hi, I signed up for the wrong plan. Can I get a refund and sign up for the correct one?",
  "Urgent: we have an all-hands in 10 min and the screen share isn't working.",
  "How long does the free trial last?",
  "Do you offer non-profit discounts?",
  "I'm having trouble logging in with Google SSO. It redirects back to the login page.",
  "Can you add my colleague Jane to our account? Her email is jane@example.com.",
  "What's the uptime SLA for enterprise customers?",
  "Is there a status page I can monitor for incidents?",
  "Dear Customer Support, I would like to formally cancel our contract.",
  "Hi, I was referred by a colleague. Do you have a referral discount program?",
  "My name is Alex and I'd like to schedule a call to discuss upgrading to enterprise.",
  "We need to be invoiced in GBP, not USD.",
  "The system sent me a verification email but I never received it.",
  "Can you extend our trial by 2 weeks? We haven't had time to fully evaluate it.",
  "I received an email saying my password was changed, but I didn't change it.",
  "Please send our Q1 invoice to finance@example.com.",
  "Hi, I'm locked out. Last login was from a new device and now 2FA isn't working.",
  "We need a custom contract. Can you connect us with your legal team?",
  "Hi, just checking — is your system GDPR compliant?",
  "Please remove all data associated with our account. We're closing the company.",
  "How do I transfer my personal account to a company account?",
  "We're moving to a new billing cycle. Can you prorate the difference?",
  "Hi, I'm reaching out about a potential acquisition. Who should I contact?",
  "Can we get historical invoice PDFs going back to 2021?",
  "My API key was accidentally leaked. Please rotate it immediately.",
  "We want to add 10 seats but only for 6 months. Can we do a partial-year add-on?",
  "The email verification link has expired. Can you resend it?",
  "Hi, I work at a startup and we're looking for tools. Is there a startup discount?",
  "Can I pay annually with a bank transfer instead of credit card?",
  "Do you accept PO numbers for enterprise invoices?",
  "Can I get a 14-day extension on my trial?",
  "Hi, the SSO login worked fine yesterday but now it's failing. No changes on our end.",
  "Our procurement team needs a vendor questionnaire filled out before we can sign.",
  "Can you adjust our invoice date to the 1st of the month?",
  "I accidentally deleted my account. Can you restore it?",
  "We need your DPA (Data Processing Agreement) for our legal team.",
  "My team member is having trouble accepting their invitation. The link says expired.",
  "Hi, I'd like to understand the difference between your plans.",
  "Can we get a trial for our US team as well? We already have one for EU.",
  "Please update the address on our invoices to 123 Main St.",
  "I was charged for a seat we deactivated 3 months ago.",
  "Hi, just making sure — do you have a mobile app?",
  "Our finance team wants to know if we can pay by check.",
  "The welcome email was very helpful! Just wanted to say that.",
  "Can you break down what's included in the business plan vs enterprise?",
  "I want to add a domain to the SSO allowlist. Who do I contact?",
  "Please change our company name on the account to reflect our rebrand.",
  "We need a copy of our contract for an internal audit.",
  "Hi, I believe there's a mistake in this month's invoice.",
  "Our contract expires in 2 weeks. Can we renew for 2 years at a discount?",
  "I'm trying to add a payment method but the form keeps giving a validation error.",
  "Can you create a separate workspace for our sandbox environment?",
  "Hi, just wanted to confirm receipt of our payment from yesterday.",
  "We'd like to request an SLA agreement for our enterprise tier.",
  "The unsubscribe link in your emails doesn't work.",
  "I'm trying to log in but keep getting a 'too many requests' error.",
  "Hi, is there a way to transfer our subscription to a different email address?",
  "We need our account data exported before we cancel at end of month.",
]
