export type { ConnectorAdapter } from "./adapter"
export { SlackAdapter } from "./slack"
export { IntercomAdapter } from "./intercom"
export { HubSpotAdapter, lookupContactByEmail as lookupHubSpotContactByEmail, lookupCompanyByDomain, mapLifecyclestageToTier } from "./hubspot"
export { SalesforceAdapter, lookupContactByEmail as lookupSalesforceContactByEmail } from "./salesforce"
